env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/Powerfull11/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[!0e16c619ac68287a2f2d36f5ba6e37b6390ee31a451dbf9d5c7c237b25c481c525907a41c60b7f1a2940324580cf7440!]
    TG_TOKEN: ENCRYPTED[!2b7cad0e473f02c00d0d2bb411b935a841b41a921d092c51d9d7c6eaffc5fe00d03523f623afccd7625fdbf75f869ede!]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/upload.sh)"
